[build]
  publish = "public"
  command = "NODE_ENV=production npm install && npm run build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
